apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
  labels:
    app: story
spec:
  replicas: 3
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: kodega2016/story-app
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: story-app-data
              mountPath: /app/story
      volumes:
        - name: story-app-data
          persistentVolumeClaim:
            claimName: story-app-persistent-volume-claim
          # emptyDir: {}
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
